### ISSUE TITLE
Remove course data

### ISSUE THREAD

**Issue by taylortom** [cgkineo/adapt_framework#5]
This seems unnecessary to me; we don't include any components/menus in core, so it's not as if the framework will work on its own. The videos in particular add a considerable amount to the size of the download. These are also often left in builds by accident (although the grunt clean is generally sorting this).

I'd suggest maybe moving this into a separate repo if it's needed at all, and just keeping very bare-bones versions of the json files.

**Comment by tomgreenfield** [comment]
Course data was removed in https://github.com/cgkineo/adapt_framework/commit/1503b287407b3f0cc369aded6e88d54078f8d689.

See [cgkineo/test](https://github.com/cgkineo/test) for the original 'm05' course and [cgkineo/p101](https://github.com/cgkineo/p101) for the stripped down course.
